//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilterTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationDefault
    {
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<int> FilterAge { get; set; }
        public Nullable<int> ReassessDays { get; set; }
        public Nullable<int> ContactAttemptsBeforeRegisteredLetter { get; set; }
        public Nullable<int> PatientContactDays { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime UpdateTimestamp { get; set; }
        public int UpdateUserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual User User1 { get; set; }
    }
}
