//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilterTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientContactAttempt
    {
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public int PatientFilterId { get; set; }
        public int ContactTypeId { get; set; }
        public int ContactResultCodeId { get; set; }
        public Nullable<int> RelatedTaskId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Notes { get; set; }
        public string TrackingNumber { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime UpdateTimestamp { get; set; }
        public int UpdateUserId { get; set; }
    
        public virtual ContactResultCode ContactResultCode { get; set; }
        public virtual ContactType ContactType { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual PatientFilter PatientFilter { get; set; }
    }
}
