//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilterTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientFilter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientFilter()
        {
            this.PatientContactAttempts = new HashSet<PatientContactAttempt>();
            this.PhysicianContactAttempts = new HashSet<PhysicianContactAttempt>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> FilterId { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public bool IsTemporary { get; set; }
        public Nullable<int> IndicationId { get; set; }
        public Nullable<int> ComplicatingFactorId { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<System.DateTime> TargetRemovalDate { get; set; }
        public Nullable<System.DateTime> ActualRemovalDate { get; set; }
        public Nullable<System.DateTime> ReassessmentDate { get; set; }
        public Nullable<int> OrderingPhysicianId { get; set; }
        public Nullable<int> PrimaryCarePhysicianId { get; set; }
        public Nullable<int> ProcedurePhysicianId { get; set; }
        public Nullable<System.DateTime> MadePermanent { get; set; }
        public string MadePermanentBy { get; set; }
        public bool IsPCPApproved { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime UpdateTimestamp { get; set; }
        public int UpdateUserId { get; set; }
    
        public virtual ComplicatingFactor ComplicatingFactor { get; set; }
        public virtual Filter Filter { get; set; }
        public virtual Indication Indication { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientContactAttempt> PatientContactAttempts { get; set; }
        public virtual Physician OrderingPhysician { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Physician PrimaryCarePhysician { get; set; }
        public virtual User ProcedurePhysician { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicianContactAttempt> PhysicianContactAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
