//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilterTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAttachment
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int AttachmentId { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime UpdateTimestamp { get; set; }
        public int UpdateUserId { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
