//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIPSCalculator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilterTrackerEntities : DbContext
    {
        public FilterTrackerEntities()
            : base("name=FilterTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationLog> ApplicationLogs { get; set; }
        public virtual DbSet<ContactResultCode> ContactResultCodes { get; set; }
        public virtual DbSet<Filter> Filters { get; set; }
        public virtual DbSet<Indication> Indications { get; set; }
        public virtual DbSet<OrganizationFilter> OrganizationFilters { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ComplicatingFactor> ComplicatingFactors { get; set; }
        public virtual DbSet<Physician> Physicians { get; set; }
        public virtual DbSet<TaskType> TaskTypes { get; set; }
        public virtual DbSet<OrganizationDefault> OrganizationDefaults { get; set; }
        public virtual DbSet<PatientQuestion> PatientQuestions { get; set; }
        public virtual DbSet<PhysicianQuestion> PhysicianQuestions { get; set; }
        public virtual DbSet<PatientQuestionResponses> PatientQuestionResponses { get; set; }
        public virtual DbSet<PhysicianQuestionResponses> PhysicianQuestionResponses { get; set; }
        public virtual DbSet<PatientFilter> PatientFilters { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<PatientContactAttempt> PatientContactAttempts { get; set; }
        public virtual DbSet<TaskAttachment> TaskAttachments { get; set; }
        public virtual DbSet<PhysicianContactAttempt> PhysicianContactAttempts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<LoginHistory> LoginHistories { get; set; }
        public virtual DbSet<MIPSHistory> MIPSHistories { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
    }
}
