//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIPSCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianQuestionResponses
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int OrganizationId { get; set; }
        public int QuestionId { get; set; }
        public string Response { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime UpdateTimestamp { get; set; }
        public int UpdateUserId { get; set; }
    
        public virtual Organization Organizations { get; set; }
        public virtual PhysicianQuestion PhysicianQuestions { get; set; }
        public virtual Task Task { get; set; }
    }
}
