//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIPSCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.PatientContactAttempts = new HashSet<PatientContactAttempt>();
            this.PatientQuestionResponses = new HashSet<PatientQuestionResponses>();
            this.PhysicianContactAttempts = new HashSet<PhysicianContactAttempt>();
            this.PhysicianQuestionResponses = new HashSet<PhysicianQuestionResponses>();
            this.TaskAttachments = new HashSet<TaskAttachment>();
        }
    
        public int Id { get; set; }
        public int TaskTypeId { get; set; }
        public int OrganizationId { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> PatientFilterId { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public System.DateTime TargetCloseDate { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime UpdateTimestamp { get; set; }
        public int UpdateUserId { get; set; }
    
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientContactAttempt> PatientContactAttempts { get; set; }
        public virtual PatientFilter PatientFilter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientQuestionResponses> PatientQuestionResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicianContactAttempt> PhysicianContactAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicianQuestionResponses> PhysicianQuestionResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAttachment> TaskAttachments { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
